version: '3'
services:
  database:
    image: postgres:15-alpine
    restart: always
    ports:
      - "$POSTGRES_PORT:$POSTGRES_PORT"
    environment:
      POSTGRES_DB: short-url-db
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    volumes:
      - ./postgres:/var/lib/postgresql/data
  redis:
    restart: always
    container_name: redis
    image: redis:7.0-alpine
    ports:
      - "$REDIS_PORT:$REDIS_PORT"
    volumes:
      - ./redis:/data